### ISSUE TITLE
Test and thus installation fails for weird reasons

### ISSUE THREAD

**Issue by JJ** [scriptkitties/perl6-app-assixt#3]
```
$ perl6 -Ilib t/command-bump.t
Usage:
  t/command-bump.t [--output-dir=<Str>] [--force] [--verbose] dist <path> 
  t/command-bump.t [--output-dir=<Str>] [--force] [--verbose] dist 
  t/command-bump.t [--output-dir=<Str>] [--force] [--verbose] dist <paths> 
```
This makes zef install fail. In fact, the error seems to be somewhere in `Bump.pm6` but I can't figure it out.

**Comment by Tyil** [comment]
Which Perl 6 version are you using, and which version of `App::Assixt` are you trying to install?

**Comment by JJ** [comment]
So far, 2018.01 and installation failed with zef and also from the source
in GitHub.

**Comment by JJ** [comment]
Trying to install now with 2018.03, different error, not your fault, I
guess..

```
The iterator of this Seq is already in use/consumed by another Seq
(you might solve this by adding .cache on usages of the Seq, or
by assigning the Seq into an array)
  in sub assert-sorted at t/08-sorted-keys.t line 8
  in block <unit> at t/08-sorted-keys.t line 11
```

**Comment by JJ** [comment]
Um, not really. It's a problem with a version of another module. I'm trying
to find out which one.

2018-03-19 17:46 GMT+01:00 JJ Merelo <jjmerelo@gmail.com>:

> Trying to install now with 2018.03, different error, not your fault, I
> guess..
>
> ```
> The iterator of this Seq is already in use/consumed by another Seq
> (you might solve this by adding .cache on usages of the Seq, or
> by assigning the Seq into an array)
>   in sub assert-sorted at t/08-sorted-keys.t line 8
>   in block <unit> at t/08-sorted-keys.t line 11
> ```
>



-- 
JJ

**Comment by Tyil** [comment]
Added 2018.03 to the Travis test targets, which fails with the error you described: https://travis-ci.org/scriptkitties/perl6-app-assixt/jobs/355751125. Updated my local Perl 6 to 2018.03 as well so I can start debugging it.

**Comment by Tyil** [comment]
Alright, after some testing, I found some issues. The failing test *should* be fixed in the latest commit, but it did show me there was something else wrong which needs fixing, probably in `App::Assixt::Commands::Push`, so I'll look if I can fix that before making a new release of it.

**Comment by Tyil** [comment]
v0.2.0 has been released, which should fix this issue. It may take a little bit before it's available through zef, but it usually doesn't take too long. Thanks for reporting the bug!
