### ISSUE TITLE
Unable to install App::Assixt

### ISSUE THREAD

**Issue by sylints** [scriptkitties/perl6-app-assixt#6]
Running Ubuntu 16.04

herby@VB:~/projects/dicerTutorial$ zef install --force-resolve App::Assixt
===> Searching for: App::Assixt
===> Searching for missing dependencies: Config::Parser::toml:ver<1.0.1+>, Config:ver<1.3.3+>, Dist::Helper:ver<0.19.2+>, Terminal::Getpass:ver<0.0.5+>
===> Searching for missing dependencies: Hash::Merge, Config::TOML, JSON::Fast:ver<0.9.11+>, SemVer:ver<0.1.3+>, Term::termios:auth<github:krunen>
===> Searching for missing dependencies: Crane
===> Building: Term::termios:auth<github:krunen>
===> Building [OK] for Term::termios:auth<github:krunen>
===> Testing: Hash::Merge:ver<0.2.0>:auth<github:scriptkitties>
Cannot merge an undefined Hash!
  in method merge at /home/herby/.zef/store/Hash-Merge-0.2.0.tar.gz/Hash-Merge-0.2.0/lib/Hash/Merge.pm6 line 22
Cannot merge an undefined Hash!
  in method merge at /home/herby/.zef/store/Hash-Merge-0.2.0.tar.gz/Hash-Merge-0.2.0/lib/Hash/Merge.pm6 line 22
===> Testing [OK] for Hash::Merge:ver<0.2.0>:auth<github:scriptkitties>
===> Testing: Config:ver<1.3.3>:auth<github:scriptkitties>
${:a("b"), :c(${:d("e")})}
===> Testing [FAIL]: Config:ver<1.3.3>:auth<github:scriptkitties>
Aborting due to test failure: Config:ver<1.3.3>:auth<github:scriptkitties> (use --force-test to override)
  in code  at /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/site/sources/9062A39D0256C0BD797016C3FE93D839191AFE2B (Zef::Client) line 385
  in method test at /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/site/sources/9062A39D0256C0BD797016C3FE93D839191AFE2B (Zef::Client) line 363
  in code  at /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/site/sources/9062A39D0256C0BD797016C3FE93D839191AFE2B (Zef::Client) line 540
  in sub  at /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/site/sources/9062A39D0256C0BD797016C3FE93D839191AFE2B (Zef::Client) line 537
  in method install at /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/site/sources/9062A39D0256C0BD797016C3FE93D839191AFE2B (Zef::Client) line 643
  in sub MAIN at /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/site/sources/9E04C517E18C976DC9F459E2CE31A87142034020 (Zef::CLI) line 152
  in block <unit> at /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/site/resources/25ADD3DE4D08C272AC81C82BCB2DBE07D909E768 line 3
  in sub MAIN at /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/site/bin/zef line 2
  in block <unit> at /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/site/bin/zef line 2

herby@VB:~/projects/dicerTutorial$ perl6 --version
This is Rakudo Star version 2018.01 built on MoarVM version 2018.01
implementing Perl 6.c.

**Comment by Tyil** [comment]
Thanks for the bug report. It seems one of the dependencies, `Config`, is failing a test. I also happen to be the author of that, so I can still handle it. I'll be looking at it tomorrow, when my mind is fresh again!

**Comment by Tyil** [comment]
New version of `Config` has been pushed to CPAN. It should resolve this issue. If it does, I'll bump the minimum required version of `Config` in the `META6.json` of this module and close the issue.

**Comment by Tyil** [comment]
Tested in the rakudo-star docker container, Config:ver<1.3.4> no longer fails installing.

**Comment by sylints** [comment]
Tyil, my install failed further downstream this time:

herby@VB:~$ zef install App::Assixt
===> Searching for: App::Assixt
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan.json
===> Updated p6c mirror: http://ecosystem-api.p6c.org/projects.json
===> Searching for missing dependencies: Config::Parser::toml:ver<1.0.1+>, Config:ver<1.3.3+>, Dist::Helper:ver<0.19.2+>, Terminal::Getpass:ver<0.0.5+>
===> Searching for missing dependencies: Hash::Merge, Config::TOML, JSON::Fast:ver<0.9.11+>, SemVer:ver<0.1.3+>, Term::termios:auth<github:krunen>
===> Searching for missing dependencies: Crane
===> Building: Term::termios:auth<github:krunen>
===> Building [OK] for Term::termios:auth<github:krunen>
===> Testing: Hash::Merge:ver<0.2.0>:auth<github:scriptkitties>
Cannot merge an undefined Hash!
  in method merge at /home/herby/.zef/store/Hash-Merge-0.2.0.tar.gz/Hash-Merge-0.2.0/lib/Hash/Merge.pm6 line 22
Cannot merge an undefined Hash!
  in method merge at /home/herby/.zef/store/Hash-Merge-0.2.0.tar.gz/Hash-Merge-0.2.0/lib/Hash/Merge.pm6 line 22
===> Testing [OK] for Hash::Merge:ver<0.2.0>:auth<github:scriptkitties>
===> Testing: Config:ver<1.3.4>:auth<github:scriptkitties>
===> Testing [OK] for Config:ver<1.3.4>:auth<github:scriptkitties>
===> Testing: Crane:ver<0.1.0>:auth<atweiden>
===> Testing [OK] for Crane:ver<0.1.0>:auth<atweiden>
===> Testing: Config::TOML:ver<0.0.1>:auth<atweiden>
===> Testing [OK] for Config::TOML:ver<0.0.1>:auth<atweiden>
===> Testing: Config::Parser::toml:ver<1.0.1>:auth<github:scriptkitties>
===> Testing [OK] for Config::Parser::toml:ver<1.0.1>:auth<github:scriptkitties>
===> Testing: JSON::Fast:ver<0.9.11>
===> Testing [OK] for JSON::Fast:ver<0.9.11>
===> Testing: SemVer:ver<0.2.0>
===> Testing [OK] for SemVer:ver<0.2.0>
===> Testing: Dist::Helper:ver<0.19.2>:auth<github:scriptkitties>
===> Testing [OK] for Dist::Helper:ver<0.19.2>:auth<github:scriptkitties>
===> Testing: Term::termios:auth<github:krunen>
===> Testing [OK] for Term::termios:auth<github:krunen>
===> Testing: Terminal::Getpass:ver<0.0.6>
===> Testing [OK] for Terminal::Getpass:ver<0.0.6>
===> Testing: App::Assixt:ver<0.2.2>
This module tests the actual program that is being installed. As a
result, it will run perl6 for every test case. This makes testing of this
module very slow. Please be patient.
===SORRY!===
Could not find Config at line 5 in:
    /home/herby/.zef/store/App-Assixt-0.2.2.tar.gz/App-Assixt-0.2.2/lib
    /home/herby/.perl6
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/site
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/vendor
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6
    CompUnit::Repository::AbsolutePath<65591920>
    CompUnit::Repository::NQP<44055864>
    CompUnit::Repository::Perl5<44055904>
# Failed test 'assixt new Local::Test::Bootstrap Config'
# at t/02-command-bootstrap-config.t line 17
===SORRY!===
Could not find Config at line 5 in:
    /home/herby/.zef/store/App-Assixt-0.2.2.tar.gz/App-Assixt-0.2.2/lib
    /home/herby/.perl6
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/site
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/vendor
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6
    CompUnit::Repository::AbsolutePath<79295936>
    CompUnit::Repository::NQP<57752888>
    CompUnit::Repository::Perl5<57752928>
    # Failed test 'assixt bootstrap config assixt.distdir /tmp'
    # at t/02-command-bootstrap-config.t line 22
    # Failed test 'Updated config option saved correctly'
    # at t/02-command-bootstrap-config.t line 36
    # expected: '/tmp'
    #      got: '/home/herby/.local/var/assixt/dists'
    # Looks like you failed 2 tests of 3
# Failed test 'Set configuration option'
# at t/02-command-bootstrap-config.t line 19
# Looks like you failed 2 tests of 2
===SORRY!===
Could not find Config at line 5 in:
    /home/herby/.zef/store/App-Assixt-0.2.2.tar.gz/App-Assixt-0.2.2/lib
    /home/herby/.perl6
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/site
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/vendor
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6
    CompUnit::Repository::AbsolutePath<70316480>
    CompUnit::Repository::NQP<48774456>
    CompUnit::Repository::Perl5<48774496>
# Failed test 'assixt new Local::Test::Bump'
# at t/02-command-bump.t line 17
Failed to change the working directory to '/tmp/bHCqqrWUCU/perl6-Local-Test-Bump': does not exist
  in block <unit> at t/02-command-bump.t line 19

# Looks like you planned 4 tests, but ran 1
# Looks like you failed 1 test of 1
===SORRY!===
Could not find Config at line 5 in:
    /home/herby/.zef/store/App-Assixt-0.2.2.tar.gz/App-Assixt-0.2.2/lib
    /home/herby/.perl6
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/site
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/vendor
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6
    CompUnit::Repository::AbsolutePath<61311520>
    CompUnit::Repository::NQP<39775544>
    CompUnit::Repository::Perl5<39775584>
# Failed test 'assixt new Local::Test::Clean'
# at t/02-command-clean.t line 17
Failed to change the working directory to '/tmp/g3BngZnJvL/perl6-Local-Test-Clean': does not exist
  in block <unit> at t/02-command-clean.t line 18

# Looks like you planned 4 tests, but ran 1
# Looks like you failed 1 test of 1
===SORRY!===
Could not find Config at line 5 in:
    /home/herby/.zef/store/App-Assixt-0.2.2.tar.gz/App-Assixt-0.2.2/lib
    /home/herby/.perl6
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/site
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/vendor
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6
    CompUnit::Repository::AbsolutePath<83522976>
    CompUnit::Repository::NQP<61988152>
    CompUnit::Repository::Perl5<61988192>
# Failed test 'assixt new Local::Test::Depend'
# at t/02-command-depend.t line 17
Failed to change the working directory to '/tmp/zinZ8r2yks/perl6-Local-Test-Depend': does not exist
  in block <unit> at t/02-command-depend.t line 18

# Looks like you planned 2 tests, but ran 1
# Looks like you failed 1 test of 1
===SORRY!===
Could not find Config at line 5 in:
    /home/herby/.zef/store/App-Assixt-0.2.2.tar.gz/App-Assixt-0.2.2/lib
    /home/herby/.perl6
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/site
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/vendor
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6
    CompUnit::Repository::AbsolutePath<72724896>
    CompUnit::Repository::NQP<51182904>
    CompUnit::Repository::Perl5<51182944>
# Failed test 'assixt new Local::Test::Dist'
# at t/02-command-dist.t line 20
Failed to change the working directory to '/tmp/HXwafgILMk/perl6-Local-Test-Dist': does not exist
  in block <unit> at t/02-command-dist.t line 21

# Looks like you planned 5 tests, but ran 1
# Looks like you failed 1 test of 1
===SORRY!===
Could not find Config at line 5 in:
    /home/herby/.zef/store/App-Assixt-0.2.2.tar.gz/App-Assixt-0.2.2/lib
    /home/herby/.perl6
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/site
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/vendor
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6
    CompUnit::Repository::AbsolutePath<68331360>
    CompUnit::Repository::NQP<46788120>
    CompUnit::Repository::Perl5<46788160>
# Failed test 'USAGE is shown when no commands are passed'
# at t/02-command-help.t line 12
===SORRY!===
Could not find Config at line 5 in:
    /home/herby/.zef/store/App-Assixt-0.2.2.tar.gz/App-Assixt-0.2.2/lib
    /home/herby/.perl6
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/site
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/vendor
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6
    CompUnit::Repository::AbsolutePath<67839888>
    CompUnit::Repository::NQP<46296600>
    CompUnit::Repository::Perl5<46296640>
# Failed test 'Help command does not fail'
# at t/02-command-help.t line 13
===SORRY!===
Could not find Config at line 5 in:
    /home/herby/.zef/store/App-Assixt-0.2.2.tar.gz/App-Assixt-0.2.2/lib
    /home/herby/.perl6
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/site
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/vendor
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6
    CompUnit::Repository::AbsolutePath<82663280>
    CompUnit::Repository::NQP<61120024>
    CompUnit::Repository::Perl5<61120064>
# Failed test '--help option does not fail'
# at t/02-command-help.t line 14
# Looks like you failed 3 tests of 3
===SORRY!===
Could not find Config at line 5 in:
    /home/herby/.zef/store/App-Assixt-0.2.2.tar.gz/App-Assixt-0.2.2/lib
    /home/herby/.perl6
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/site
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/vendor
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6
    CompUnit::Repository::AbsolutePath<53212640>
    CompUnit::Repository::NQP<31669560>
    CompUnit::Repository::Perl5<31669600>
    # Failed test 'assixt new'
    # at t/02-command-new.t line 31
    # Failed test 'Module directory created'
    # at t/02-command-new.t line 43
    # Failed test 'Gitignore created'
    # at t/02-command-new.t line 44
    # Failed test 'Editorconfig created'
    # at t/02-command-new.t line 45
    # Failed test 'Travis config created'
    # at t/02-command-new.t line 46
No META6.json in /tmp/T290pAzTwa/perl6-Local-Test-Module
  in sub get-meta at /home/herby/.zef/store/Dist-Helper-0.19.2.tar.gz/Dist-Helper-0.19.2/lib/Dist/Helper/Meta.pm6 (Dist::Helper::Meta) line 14
  in block  at t/02-command-new.t line 51
  in sub subtest at /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/sources/C712FE6969F786C9380D643DF17E85D06868219E (Test) line 414
  in sub subtest at /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/sources/C712FE6969F786C9380D643DF17E85D06868219E (Test) line 405
  in block <unit> at t/02-command-new.t line 26

===SORRY!===
Could not find Config at line 5 in:
    /home/herby/.zef/store/App-Assixt-0.2.2.tar.gz/App-Assixt-0.2.2/lib
    /home/herby/.perl6
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/site
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/vendor
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6
    CompUnit::Repository::AbsolutePath<82777600>
    CompUnit::Repository::NQP<61234488>
    CompUnit::Repository::Perl5<61234528>
# Failed test 'assixt new Local::Test::Touch::Bin'
# at t/02-command-touch-bin.t line 17
Failed to change the working directory to '/tmp/rzuA6AmaEu/perl6-Local-Test-Touch-Bin': does not exist
  in block <unit> at t/02-command-touch-bin.t line 18

# Looks like you planned 2 tests, but ran 1
# Looks like you failed 1 test of 1
===SORRY!===
Could not find Config at line 5 in:
    /home/herby/.zef/store/App-Assixt-0.2.2.tar.gz/App-Assixt-0.2.2/lib
    /home/herby/.perl6
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/site
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/vendor
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6
    CompUnit::Repository::AbsolutePath<55232976>
    CompUnit::Repository::NQP<33697080>
    CompUnit::Repository::Perl5<33697120>
# Failed test 'assixt new Local::Test::Touch::Lib::Class'
# at t/02-command-touch-class.t line 17
Failed to change the working directory to '/tmp/KwsHgzxD5A/perl6-Local-Test-Touch-Lib-Class': does not exist
  in block <unit> at t/02-command-touch-class.t line 18

# Looks like you planned 2 tests, but ran 1
# Looks like you failed 1 test of 1
===SORRY!===
Could not find Config at line 5 in:
    /home/herby/.zef/store/App-Assixt-0.2.2.tar.gz/App-Assixt-0.2.2/lib
    /home/herby/.perl6
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/site
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/vendor
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6
    CompUnit::Repository::AbsolutePath<75191776>
    CompUnit::Repository::NQP<53648696>
    CompUnit::Repository::Perl5<53648736>
# Failed test 'assixt new Local::Test::Touch::Resource'
# at t/02-command-touch-resource.t line 17
Failed to change the working directory to '/tmp/2TUKP9BIjV/perl6-Local-Test-Touch-Resource': does not exist
  in block <unit> at t/02-command-touch-resource.t line 18

# Looks like you planned 2 tests, but ran 1
# Looks like you failed 1 test of 1
===SORRY!===
Could not find Config at line 5 in:
    /home/herby/.zef/store/App-Assixt-0.2.2.tar.gz/App-Assixt-0.2.2/lib
    /home/herby/.perl6
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/site
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/vendor
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6
    CompUnit::Repository::AbsolutePath<57460176>
    CompUnit::Repository::NQP<35917112>
    CompUnit::Repository::Perl5<35917152>
# Failed test 'assixt new Local::Test::Touch::Test'
# at t/02-command-touch-test.t line 16
Failed to change the working directory to '/tmp/WR4PV1zslq/perl6-Local-Test-Touch-Test': does not exist
  in block <unit> at t/02-command-touch-test.t line 17

# Looks like you planned 2 tests, but ran 1
# Looks like you failed 1 test of 1
===SORRY!===
Could not find Config at line 5 in:
    /home/herby/.zef/store/App-Assixt-0.2.2.tar.gz/App-Assixt-0.2.2/lib
    /home/herby/.perl6
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/site
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/vendor
    /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6
    CompUnit::Repository::AbsolutePath<79230448>
    CompUnit::Repository::NQP<57687352>
    CompUnit::Repository::Perl5<57687392>
# Failed test 'assixt new Local::Test::Touch::Lib::Unit'
# at t/02-command-touch-unit.t line 17
Failed to change the working directory to '/tmp/tmm1mFHYHm/perl6-Local-Test-Touch-Lib-Unit': does not exist
  in block <unit> at t/02-command-touch-unit.t line 18

# Looks like you planned 2 tests, but ran 1
# Looks like you failed 1 test of 1
===> Testing [FAIL]: App::Assixt:ver<0.2.2>
Aborting due to test failure: App::Assixt:ver<0.2.2> (use --force-test to override)
  in code  at /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/site/sources/8244C3B17ACA61B0EC04857BB3283A8FAF7A186D (Zef::Client) line 374
  in method test at /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/site/sources/8244C3B17ACA61B0EC04857BB3283A8FAF7A186D (Zef::Client) line 354
  in code  at /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/site/sources/8244C3B17ACA61B0EC04857BB3283A8FAF7A186D (Zef::Client) line 523
  in sub  at /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/site/sources/8244C3B17ACA61B0EC04857BB3283A8FAF7A186D (Zef::Client) line 520
  in method install at /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/site/sources/8244C3B17ACA61B0EC04857BB3283A8FAF7A186D (Zef::Client) line 621
  in sub MAIN at /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/site/sources/81436475BD18D66BFD96BBCEE07CCCDC0F368879 (Zef::CLI) line 152
  in block <unit> at /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/site/resources/D822DF07A6D5CB602F97ED307F62A1B3B5D2C90D line 3
  in sub MAIN at /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/site/bin/zef line 2
  in block <unit> at /home/herby/rakudo/rakudo-star-2018.01/install/share/perl6/site/bin/zef line 2

**Comment by Tyil** [comment]
A new release has been made to solve this.

**Comment by sylints** [comment]
Successfully installed.  Thanks for the help.
